# Generated by Django 4.1.2 on 2022-11-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="avatares"),
        ),
    ]
