# Generated by Django 4.1.2 on 2022-11-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogApp", "0002_alter_avatar_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="imagenes"),
        ),
    ]
