# Generated by Django 4.1.2 on 2022-11-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogApp", "0003_articulo_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulo",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
