# Generated by Django 4.1.2 on 2022-11-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogApp", "0004_alter_articulo_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articulo",
            name="imagen",
        ),
    ]
