# Generated by Django 4.1.2 on 2022-11-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mensaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destinatario",
                    models.CharField(
                        choices=[("Argentina", "Argentina"), ("Brasil", "Brasil")],
                        max_length=100,
                    ),
                ),
                ("mensaje_escrito", models.CharField(max_length=100)),
                ("fecha", models.DateField(null=True)),
            ],
            options={
                "verbose_name_plural": "Mensajes",
            },
        ),
    ]
